---
apiVersion: v1
kind: Pod
metadata:
  name: billing
  labels:
    app: billing
  namespace: test
spec:
  restartPolicy: OnFailure
  containers:
    - name: billing
      image: anantac/billing:release-1
      imagePullPolicy: Always
      volumeMounts:
        mountPath: "/root/ssl"
        readOnly: true
  volumes:
  - name: certs
    secret:
      secretName: billing-check-server-cert
      optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: billing-check-webhook
  namespace: test
spec:
  selector:
    app: billing
  ports:
  - port: 443
    targetPort: 5000
